"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const user_controller_1 = require("../controllers/user.controller");
const auth_middleware_1 = require("../middlewares/auth.middleware");
const router = (0, express_1.Router)();
router.post('/validate-password', auth_middleware_1.authMiddleware, user_controller_1.userController.validatePassword);
router.post('/', user_controller_1.userController.createUser);
router.get('/', auth_middleware_1.authMiddleware, user_controller_1.userController.getAllUsers);
router.get('/:id', auth_middleware_1.authMiddleware, user_controller_1.userController.getUserById);
router.put('/:id', auth_middleware_1.authMiddleware, user_controller_1.userController.updateUser);
router.delete('/:id', auth_middleware_1.authMiddleware, user_controller_1.userController.deleteUser);
exports.default = router;
